### ISSUE TITLE
Models for ImageNet

### ISSUE THREAD

**Issue by motokimura** [machine-perception-robotics-group/attention_branch_network#1]
コードの共有をいただきありがとうございます。

ImageNetでpre-train済みのモデルを使って推論を試してみようと思ったのですが、モデル（ResNet50/101/152）のpythonファイルが`models/imagenet`以下に見当たりません（`models/imagenet`以下にある`resnext.py`で定義されているモデルも`forward`ではアテンションマップを返していないように見えます）。

公開いただいているImageNetのpre-trainモデルをロードして推論を行いたい場合、どのpythonファイルで定義されているネットワークに対して、pre-trainモデルをロードすればよろしいでしょうか？

**Comment by Hiroshi-Fukui** [comment]
コメントありがとうございます．

ResNetのpythonファイルをアップロードできていませんでした．
以下に新しくResNetを追加致しました．
https://github.com/machine-perception-robotics-group/attention_branch_network/blob/master/models/imagenet/resnet.py

SENetのpythonファイルも一緒に公開しましたが，こちらのモデルファイルの公開は後日にアップロードする予定ですので，少々お待ち下さい．

**Comment by motokimura** [comment]
お返事遅くなってしまい申し訳ありません。

ResNetのpythonファイルの追加ありがとうございました。
Google Colaboratory上で無事に動作させることができました。https://github.com/motokimura/attention_branch_network_demo/blob/master/attention_branch_network_demo.ipynb

SENetのモデルファイルの方もありがとうございます。お待ちしております。
