### ISSUE TITLE
Manage Dockerfile in this repo.

### ISSUE THREAD

**Issue by takayuki5168** [machine-perception-robotics-group/attention_branch_network#11]
Why don't you manage your Dockerfile in this repository?

There is an obsolete bug in Dockerfile, so I want to make a PR.

**Comment by takayuki5168** [comment]
@Hiroshi-Fukui 
Now ppa:jonathonf/python-3.6 cannot be used, so we should use ppa:deadsnakes/ppa https://qiita.com/pudding167/items/1d7226155cbfcd76bb1a

**Comment by thirakawa** [comment]
@takayuki5168 
Hi. We thank for your advice.
We confirmed ppa:jonathonf/python-3.6 is no longer available.
Instead, we have prepared a new Dockerfile that builds python3.6 from source, and you can find it in the repository.

**Comment by takayuki5168** [comment]
@thirakawa Thanks a lot!
