### ISSUE TITLE
Using pretrained model

### ISSUE THREAD

**Issue by utsavdshah** [machine-perception-robotics-group/attention_branch_network#12]
Hi!

I have trained ABN on custom data from scratch using the training script and steps provided -- it works fine. However, when I try to finetune pretrained ResNet models using "--pretrained" flag, it always crashes with missing key(in state_dict) error. All the missing weights seems to be from the attention layer. Has anyone faced similar issue or know how to resolve this? Thank you.

**Comment by thirakawa** [comment]
Hi!

If you want to use pretrained model on ImageNet for initializing ABN, please add a argument (`strict=False`) in load_state_dict.
For example, resnet18 in `models/imagenet/resnet.py`:
```
def resnet18(pretrained=False, **kwargs):
    """Constructs a ResNet-18 model.
    Args:
        pretrained (bool): If True, returns a model pre-trained on ImageNet
    """
    model = ResNet(BasicBlock, [2, 2, 2, 2], **kwargs)
    if pretrained:
        model.load_state_dict(model_zoo.load_url(model_urls['resnet18']), strict=False)
    return model
```

`strict=False` loads only model parameters that are corresponding to existing layers.
This would success to load a pretrained ResNet model.

You can find the detailed description [here](https://pytorch.org/docs/0.4.0/nn.html?highlight=load_state_dict#torch.nn.Module.load_state_dict).

best.

**Comment by utsavdshah** [comment]
Thank you @thirakawa 
Adding `strict=False` solved issue!
