### ISSUE TITLE
__init__ file contains non-existent networks

### ISSUE THREAD

**Issue by isht8** [machine-perception-robotics-group/attention_branch_network#4]
[this](https://github.com/machine-perception-robotics-group/attention_branch_network/blob/master/models/cifar/__init__.py) init file contains alexnet, vgg and preresnet imports  files corresponding to which are missing. This gives an error when training cifar10.

**Comment by mymuli** [comment]
@Isht Dwivedi 
‘# ’ from .alexnet import *
‘# ’ from .vgg import *
from .resnet import *
from .resnext import *
from .wrn import *
‘# ’ from .preresnet import *
from .densenet import *

**Note out** the files that are not in the folder **models/cifar**
