### ISSUE TITLE
Can you share the code about multi-task learning?

### ISSUE THREAD

**Issue by Xiaoccer** [machine-perception-robotics-group/attention_branch_network#5]
I have some problem with the multi-task learning.

**Comment by yassouali** [comment]
Same here, would appreciate it to take a look into multi-task learning bit if possible.

**Comment by Hiroshi-Fukui** [comment]
I shared the ABN with multi-task learning. (Sorry, I late the reply...)
https://github.com/machine-perception-robotics-group/ABN_CelebA

**Comment by yassouali** [comment]
Thank you

> I shared the ABN with multi-task learning. (Sorry, I late the reply...)
> https://github.com/machine-perception-robotics-group/ABN_CelebA
Thanks
