### ISSUE TITLE
Model files corrupted on ImageNet2012 Dataset

### ISSUE THREAD

**Issue by zxwedu** [machine-perception-robotics-group/attention_branch_network#8]
When I try to run the code, I download the model files on ImageNet2012 dataset from the links in readme file. But the downloaded files are corrupted. Could you please check the files in dropbox? Thank you.

https://www.dropbox.com/sh/tuo90s1uqmbk1vd/AAAksM9uPT5u-eViAe-PXIqsa?dl=0
https://www.dropbox.com/sh/8vzv7ov59xb5wle/AABaE24vo3Kc-VuSKbOUsZiua?dl=0
https://www.dropbox.com/sh/senw3akoud9cten/AACXOBuiNCWq6wPjl4EIVmhHa?dl=0

**Comment by gtanisik** [comment]
I've only tried Resnet101 and Resnet152. 101 works but I get the same error on 152.

**Comment by Hiroshi-Fukui** [comment]
Sorry, I replaced the URL of ResNet152 + ABN.

https://www.dropbox.com/sh/4l6f650uttgub8j/AAD7HxDZ7UVZEZNPWkBNRjNCa?dl=0
